name: Run rakuTests

on:
  workflow_dispatch: # Manual trigger

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v2
      with:
        xcode-version: latest

    - name: Install dependencies
      run: swift package resolve

    - name: Run tests
      run: xcodebuild test -project raku/raku.xcodeproj -scheme raku -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'

