name: Run rakuTests

on: [workflow_dispatch]

jobs:
  run_tests:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version

    - name: Install dependencies
      run: swift package resolve

    - name: Run tests
      run: xcodebuild test -scheme raku -project raku/raku.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}

