# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Change to project directory and build
      run: |
        cd raku/raku
        swift build -v

    - name: Change to project directory and run tests
      run: |
        cd raku/raku
        swift test -v
